config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :websites, only: [:index, :create, :new, :show, :update] do

    get 'builder', to: 'websites#builder'
    resources :sections, only: [:index, :create, :update, :new, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/element.rb
class Element < ApplicationRecord
  enum category: [:h1, :h2, :h3, :p, :img, :video, :list, :product, :link, :text, :email, :phone_number]

  belongs_to :section
  has_one_attached :photo

  def youtube_vid_id()
    if self.value.size.positive?
      url = URI.parse(self.value)
      video_params = CGI.parse(url.query)
      if video_params["v"]
        video_params["v"].first
      else
        url.path[1..]
      end
    else
      ""
    end
  end
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :website
  has_many :elements, dependent: :destroy

  accepts_nested_attributes_for :elements

  def get_elements
    SECTION_CONFIG[self.name.downcase.to_sym][:elements]
  end

  def element_named(name, hash_key = nil)
    element = elements&.find_by(name: name)
    unless element.nil?
      case element.category.to_sym
      when :product
        return eval(element.value)[hash_key]
      when :img
        return element.photo.key.nil? ? element.value : element.photo.key
      else
        return element.value
      end
    end
    nil
  end

  def self.get_content_of(section, section_name, element_name, hash_key = nil)
    # section.get_content_of("greeting")
    # raise if section_name == 'catchy'
    if section&.element_named(element_name, hash_key).present?
      # return the content
      section&.element_named(element_name, hash_key)
    else
      # return default content
      element = SECTION_CONFIG[section_name.downcase.tr_s(" ", "_").to_sym][:default][element_name.downcase.tr_s(" ", "_").to_sym]
      element = element[hash_key] unless hash_key.nil?
      element
    end
  end
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  belongs_to :website
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :websites
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :websites
end

app/models/website.rb
class Website < ApplicationRecord
  DOMAIN_OPTIONS = ['englishlanguageteacher.com', 'spanishlanguageteacher.com']
  THEMES = ['younglearners', 'business', 'general', 'examspreparation']

  belongs_to :user
  belongs_to :theme, optional: true
  has_many :testimonials, dependent: :destroy
  has_many :sections, dependent: :destroy
  validates :domain, inclusion: { in: DOMAIN_OPTIONS }

  extend FriendlyId
  friendly_id :name, use: :slugged

  def section_named(name)
    sections&.find_by(name: name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # pundit for all controllers removed to Website Controller
  def default_url_options
    { host: ENV["www.hubbly.herokuapp.com/"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @websites = Website.limit(5)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @sections = Section.order(:order)
  end

  def new
    @section = Section.new(name: params[:section])
    @website = Website.friendly.find(params[:website_id])
    @section.website = @website
    @section.elements.build(@section.get_elements)
  end

  def create
    @section = Section.new(section_params)
    @website = Website.friendly.find(params[:website_id])
    @section.website = @website
    if @section.save
      redirect_to website_builder_path(@website)
    else
      render :new
    end
  end

  def update
    @section = Section.find(params[:id])
    @section.elements.destroy_all
    if @section.update(section_params)
      redirect_to website_builder_path(@section.website)
    else
      render 'websites/builder'
    end
  end


  def section_params

    params[:section][:elements_attributes].each do |k, v|
      if v[:category] == 'product'
        v[:value] = v[:value].to_s
      end
    end
    params.require(:section).permit(:name, elements_attributes: [:name, :value, :category, :photo, :label])
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  include Pundit
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def index
    @websites = policy_scope(Website)
    # if no pundit - @websites = current_user.websites
  end

  def new
    # @user = current_user
    @website = Website.new
    @website.build_theme
    authorize @website
    @themes = Theme.pluck(:name, :id)
  end


  def create
    @website = Website.new(website_params)
    @website.user = current_user
    authorize @website

    if @website.save
      redirect_to website_builder_path(@website)
    else
      render :new
    end
  end

  def show
    @website = Website.friendly.find(params[:id])
    begin
      authorize @website
    rescue Pundit::NotAuthorizedError
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    else
      # Everyone can see the page if it is published
      render layout: @website.theme.name
    end
  end

  def update
    @website = Website.friendly.find(params[:id])
    authorize @website
    if @website.update(website_params)
      redirect_to website_path(@website), notice: 'Website was updated'
    else
      redirect_to website_builder(@website)
    end
  end

  def edit
    @website = Website.friendly.find(params[:id])
    authorize @website
  end

  def builder
    @website = Website.friendly.find(params[:website_id])
    @sections = @website.sections

    @section_hero = @sections.find_by(name: "hero") || Section.new(name: "hero")
    @section_bio = @sections.find_by(name: "bio") || Section.new(name: "bio")
    @section_catchy = @sections.find_by(name: "catchy") || Section.new(name: "catchy")
    @section_pricing = @sections.find_by(name: "pricing") || Section.new(name: "pricing")
    @section_calendar = @sections.find_by(name: "calendar") || Section.new(name: "calendar")
    @section_contact = @sections.find_by(name: "contact") || Section.new(name: "contact")

    @section_hero.elements.build(@section_hero.get_elements) if @section_hero.id.nil?
    @section_bio.elements.build(@section_bio.get_elements) if @section_bio.id.nil?
    @section_catchy.elements.build(@section_catchy.get_elements) if @section_catchy.id.nil?
    @section_pricing.elements.build(@section_pricing.get_elements) if @section_pricing.id.nil?
    @section_calendar.elements.build(@section_calendar.get_elements) if @section_calendar.id.nil?
    @section_contact.elements.build(@section_contact.get_elements) if @section_contact.id.nil?

    @section_hero.website = @website
    @section_bio.website = @website
    @section_catchy.website = @website
    @section_pricing.website = @website
    @section_calendar.website = @website
    @section_contact.website = @website

    @sections_map = {
      hero: @section_hero,
      bio: @section_bio,
      catchy: @section_catchy,
      pricing: @section_pricing,
      calendar: @section_calendar,
      contact: @section_contact
    }

    authorize @website
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def website_params
    params.require(:website).permit(:name, :domain, :theme_id, :published)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>hubbly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

<!-- Title tag is set and exceeds 20 chars -->
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
<!-- favicon is set -->
    <%#= favicon_link_tag %>
  </head>

  <%# <body class="position-relative" data-controller="<%= 'navbar' if action_name == "home" %>
    <body data-controller="<%= 'navbar' if action_name == "home" %>">

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    
    <main>
      <%= yield %>
    </main>
    <%= render 'pages/footer' %>
  </body>
</html>

app/views/layouts/kids.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @website.name %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body class="kids-template">

<%# HEADER HERO %>
    <%= render 'sections/hero', section: @website&.section_named("hero") %>

<%# BIO %>
    <div class="container">
      <%= render 'sections/bio', section: @website&.section_named("bio") %>

<%# CATCHY_INFO %>

      <%= render 'sections/catchy', section: @website&.section_named("catchy") %>

<%# CALENDAR %>
      <%= render 'sections/calendar', section: @website&.section_named("calendar") %>

<%#= PRICING %>

      <%= render 'sections/pricing', section: @website&.section_named("pricing") %>

<%#= CONTACT %>

      <%= render "sections/contact", section: @website.section_named("contact") %>
    
    </div><%#= THIS CLOSES THE "CONTAINER" CLASS %>
  </body>
</html>

app/views/layouts/younglearners.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @website.name %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body class="kids-template">

<%# HEADER HERO %>
    <%= render 'sections/hero', section: @website&.section_named("hero") %>

<%# BIO %>
    <div class="container">
      <%= render 'sections/bio', section: @website&.section_named("bio") %>

<%# CATCHY_INFO %>

      <%= render 'sections/catchy', section: @website&.section_named("catchy") %>

<%# CALENDAR %>
      <%= render 'sections/calendar', section: @website&.section_named("calendar") %>

<%#= PRICING %>

      <%= render 'sections/pricing', section: @website&.section_named("pricing") %>

<%#= CONTACT %>
     
    </div><%#= THIS CLOSES THE "CONTAINER" CLASS %>
      <%= render "sections/contact", section: @website.section_named("contact") %>
  </body>
</html>

app/views/pages/_footer.html.erb
<footer class="footer">

  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Created by Hubble Hardware with <i class="fas fa-heart"></i>
  </div>

  <div class="footer-contact d-flex m-4 justify-content-center align-items-center">
    <div>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
      <a href="https://api.whatsapp.com/send?phone=+34700700700&text=Hola%21%20I%20would%20like%20more%20info%20about%20making%20great%20websites." class="float" target="_blank">
      <i class="fa fa-whatsapp my-float"></i>
      </a>
    </div>
    <div>
      <strong>Contact</strong>
      <div>
        <i class="fas fa-envelope-square"></i> info@hubbly.com
      </div>
      <div>
        <i class="fas fa-address-card"></i> Carrer de les Teachers 1,
      </div>
      <div class="ml-4">08000 Barcelona, Spain</div>
      <div>
        <i class="fas fa-phone"></i> +34 645312365
      </div>


    </div>
  </div>

</footer>

app/views/pages/home.html.erb
<%# HEADER %>

<header class="banner"> 
  <div class="container">
    <h1>Find new students & grow your business</h1>
    <p>Websites for language teachers</p>
    <a class="btn-primary" href="<%= new_website_path %>">Make my free website</a> 
      <%# <a class="btn-secondary" href="<%= root_path(anchor: "tell_more")">Tell me more</a> %>
  </div>
</header>

<%# WHAT IS HUBBLY %>
<section class="hubbly-blue">
  <div class="what-is-hubbly container">
    <div class="wih-content">
      <h1 my-5>What is Hubbly?</h1>
      <p>Watch the video to see what we do and how we can help you have a professional website up and running in just 30 minutes. No fuss, no coding and as easy to put together as teaching your students their A, B, C’s!</p>
    </div>
    <div class="wih-video">
      <iframe width="100%" height="315" src="https://www.youtube.com/embed/L7jk1EJMq08" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> 
    </div>
  </div>
</section>

<%# WHY HUBBLY - 3 CARDS %>
<section class="hubbly-pink">
  <div class="why-hubbly container">
    <h1>Why hubbly?</h1>

    <div class="cards-homepage">

      <div class="card-homepage">
        <%= image_tag "browser.png", alt: "Why a website" %>
        <h3>Why a website</h3>
        <p>We know language teachers need to continually find new students to keep their business afloat. Read our blog post on the best strategies of building a student pipeline</p>
        <a href="">Learn more</a>
      </div>

      <div class="card-homepage">
        <%= image_tag "handshake.png", alt: "How we help" %>
        <h3>How we help</h3>
        <p>Hubbly is the perfect solution to get set up and running with your own website to promote your teaching services quickly, efficiently and cost effectively.</p>
        <a href="">Learn more</a>
      </div>

      <div class="card-homepage">
        <%= image_tag "star.png", alt: "Why choose us" %>
        <h3>Why choose us</h3>
        <p>There is no learning how to code, working out UX/UI design, paying for web hosting etc… Just your own, personalised and google indexed website lickety-split!</p>
        <a href="">Learn more</a>
      </div>
    </div>
  </div>
</section>

<%# WEBSITE TEMPLATES %>
    <div class="website-templates container">
      <h1>What will my website look like?</h1>
      <h3>Pick your favourite style from our templates below</h3>
      <p>Our websites use the best UI/UX design to help you achieve the highest possible conversion rate and book new students</p>
      
      <div class="carousel">
        <section>
          <div class="scroll-arrow" id="scroll-left">
              &#8592;
            </div>
            <ul id="imgList">
              <li><img src="https://res.cloudinary.com/dwsfhweeg/image/upload/v1627825000/Hubbly/Template_-_Young_learners_svotb0.png"/></li>
              <li><img src="https://res.cloudinary.com/dwsfhweeg/image/upload/v1627824935/Hubbly/Template_-_Business_wytx6f.png"/></li>
              <li><img src="https://res.cloudinary.com/dwsfhweeg/image/upload/v1627824935/Hubbly/Template_-_Tech_executives_gytmix.png"/></li>
            </ul>
            <div class="scroll-arrow" id="scroll-right" onclick="scrollRight()">
              &#8594;
            </div>
        </section>
      </div>
    </div>


<%# PRICING NEED TO SORT THIS OUT!!! %>

<%# <div class="pricing container">
  <h1>Choose Your Plan</h1>

  <div class="cards-pricing">


    <div class="card-pricing starter-plan">
      <h3 >STARTER</h3>
      <h5>$100</h5> %>
      <%# <svg viewBox="0 0 500 500" preserveAspectRatio="xMinYMin meet">
        <path d="M0,100 C150,200 350,0 500,100 L500,00 L0,0 Z" style="stroke: none; fill:#E5F6FE;"></path>
      </svg> %>
      <%# <div class="card-content"> %>
        <%# <p>Basic domain name</p>
        <p>Website hosting for 1st year</p>
        <p>SSL security certificate</p>
        <p>Choice of website design theme</p>
        <p>Links to social media accounts</p> %>
      <%# </div> %>
    <%# </div>

    <div class="card-pricing scale-plan">
      <h3 >SCALE</h3>
      <h5>$100</h5>
    </div>
    <svg viewBox="0 0 500 500" preserveAspectRatio="xMinYMin meet">
      <path d="M0,100 C150,200 350,0 500,100 L500,00 L0,0 Z" style="stroke: none; fill:#E5F6FE;"></path>
    </svg>
    <div class="card-content">
      <p>Basic domain name</p>
      <p>Website hosting for 1st year</p>
      <p>SSL security certificate</p>
      <p>Choice of website design theme</p>
      <p>Links to social media accounts</p>
    </div>

    <div class="card-pricing premium-plan">
      <h3 >PREMIUM</h3>
      <h5>$100</h5>
    </div>
    <svg viewBox="0 0 500 500" preserveAspectRatio="xMinYMin meet">
      <path d="M0,100 C150,200 350,0 500,100 L500,00 L0,0 Z" style="stroke: none; fill:#E5F6FE;"></path>
    </svg>
    <div class="card-content">
      <p>Basic domain name</p>
      <p>Website hosting for 1st year</p>
      <p>SSL security certificate</p>
      <p>Choice of website design theme</p>
      <p>Links to social media accounts</p>
    </div>

</div> %>






<%# 

<div class="container pt-5">
  <h2 class="text-center mt-5">Choose Your Plan</h2>

  <div class="cards mt-3 justify-content-center">
    <div class="card basic-plan mt-5">

      <div class="card-category">
        <div class="d-flex flex-column align-items-center">
          <h3 >Basic</h3>
          <h5>$100</h5>
        </div>
        <svg viewBox="0 0 500 500" preserveAspectRatio="xMinYMin meet">
          <path d="M0,100 C150,200 350,0 500,100 L500,00 L0,0 Z" style="stroke: none; fill:#E5F6FE;"></path>
        </svg>
        </div>
        <div class="px-3 card-content">
          <p>Basic domain name</p>
          <p>Website hosting for 1st year</p>
          <p>SSL security certificate</p>
          <p>Choice of website design theme</p>
          <p>Links to social media accounts</p>
        </div>
      </div>

      <div class="card standard-plan">
        <div class="card-category">
          <div class="d-flex flex-column align-items-center">
            <h3 >Standard</h3>
            <h5>$150</h5>
          </div>
          <svg viewBox="0 0 500 500" preserveAspectRatio="xMinYMin meet">
            <path d="M0,100 C150,200 350,0 500,100 L500,00 L0,0 Z" style="stroke: none; fill:#E45A98;"></path>
          </svg>
        </div>
        <div class="px-3 card-content">
          <p>Basic domain name</p>
          <p>Website hosting for 1st year</p>
          <p>SSL security certificate</p>
          <p>Choice of website design theme</p>
          <p>Links to social media accounts</p>
        </div>
      </div>

      <div class="card premium-plan mt-5">
        <div class="card-category">
          <div class="d-flex flex-column align-items-center">
            <h3 >Premium</h3>
            <h5>$200</h5>
          </div>
          <svg viewBox="0 0 500 500" preserveAspectRatio="xMinYMin meet">
            <path d="M0,100 C150,200 350,0 500,100 L500,00 L0,0 Z" style="stroke: none; fill:#EDDBFF;"></path>
          </svg>
        </div>
        <div class="px-3 card-content">
          <p>Basic domain name</p>
          <p>Website hosting for 1st year</p>
          <p>SSL security certificate</p>
          <p>Choice of website design theme</p>
          <p>Links to social media accounts</p>
        </div>
      </div>

  </div>
</div> %>

<%# JAVASCRIPT FOR CAROUSEL %>

<script>
  var imgList = document.getElementById('imgList');
  var scrollRight = document.getElementById('scroll-right');
  var scrollLeft = document.getElementById('scroll-left');

// When a user clicks on the right arrow, the ul will scroll 750px to the right
  scrollRight.addEventListener('click', (event) => {
    imgList.scrollBy(750, 0);
});

// When a user clicks on the left arrow, the ul will scroll 750px to the left
  scrollLeft.addEventListener('click', (event) => {
    imgList.scrollBy(-750, 0);
});
</script>

app/views/sections/_bio.html.erb
<div class="d-flex pt-5 <%= 'is-hidden' if section&.id.nil? %>" id="preview_bio">
  <div class="bio-left">
      <h2 data-preview-greeting><%= Section.get_content_of(section, "Bio", "greeting") %></h2>
      <p data-preview-intro><%= Section.get_content_of(section, "Bio", "intro") %></p>
  </div>
  <div class="bio-right">
      <% img_url = cl_image_path(Section.get_content_of(section, "Bio", "picture")) %>
      <img data-preview-picture src= '<%= img_url %>' alt="" class="hubbly-large">
  </div>
</div>

app/views/sections/_form_pricing.html.erb
<%= form_tag section.id.nil? ? website_sections_path(website) : website_section_path(website, section), method: section.id.nil? ? :post : :patch, data: {controller: 'preview'} do %>
  <%= hidden_field_tag "section[name]", 'pricing' %>
  <% section.elements.each_with_index do |el, i| %>

    <%= hidden_field_tag "section[elements_attributes][#{i}][name]", el.name %>
    <%= hidden_field_tag "section[elements_attributes][#{i}][category]", el.category %>
    <%= hidden_field_tag "section[elements_attributes][#{i}][label]", el.label %>
    <div class="form-group">
      
      <% if el.category == "product" %>
        <%= label_tag 'Service name / online price / offline price' %>

        <div class="d-flex">    
          <%= text_field_tag "section[elements_attributes][#{i}][value][type]", eval(el.value || '{}')['type'], class: 'form-control', data: {"preview-target": "data-preview-product#{i - 1}-type", action: "input->preview#updatePreview" }%>

          <%# i - 2 to reference the correct product element PLEASE CHANGE THIS SOONER RATHER THAN LATER %>
          <%= text_field_tag "section[elements_attributes][#{i}][value][online_price]", eval(el.value || '{}')['online_price'], class: 'form-control', placeholder: 'online', data: {"preview-target": "data-preview-product#{i - 1}-online-price", action: "input->preview#updatePreview" } %>
          <%= number_field_tag "section[elements_attributes][#{i}][value][offline_price]", eval(el.value || '{}')['offline_price'], class: 'form-control', placeholder: 'offline', data: {"preview-target": "data-preview-product#{i - 1}-offline-price", action: "input->preview#updatePreview" } %>
        </div>
      <% else %>
        <%= label_tag el.label %>
        <% if el.category.to_sym == :list %>
          <%= text_area_tag "section[elements_attributes][#{i}][value]", el.value, class: 'form-control', data: {"input-type": el.category, "preview-target": "data-preview-#{el.name}", action: "input->preview#updatePreview" } %>
        <% else %>
          <%= text_field_tag "section[elements_attributes][#{i}][value]", el.value, class: 'form-control', data: {"input-type": el.category, "preview-target": "data-preview-#{el.name}", action: "input->preview#updatePreview" } %>
        <% end %>
      <% end %>
    </div>
  <% end %>
  <%= submit_tag 'Save section', class: 'btn-form' %>
<% end %>

app/views/sections/index.html.erb
<% @sections.each do |section| %>
  <%= render "sections/#{section.name}", section: section %>
<% end %>

app/views/sections/new.html.erb
<div class="row col-12 col-md-12">
  <div class="container col-12 col-md-6 mr-0">
    <div class="flat-form">
      <div class="mt-3">
        <%= render "sections/form_#{@section.name}", section: @section %>
      </div>
    </div>
  </div>
  <div class="container col-12 col-md-6 mr-0">
  Preview
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="nav-menu">
  <%= link_to "/", class: "nav-logo" do %>
    <i class="fas fa-feather-alt"></i>
    Hubbly
  <% end %>
  <div class="nav-links">
    <% if user_signed_in? %>
      <%= link_to "Dashboard", websites_path, class: "nav-link"%>
      <%= link_to "Create a Website", new_website_path, class: "nav-link"%>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "nav-link" %>
    <% end %>
  </div>
</div>

<%# <i class="fas fa-feather-alt"></i> %>

app/views/shared/xxx.html.erb
          <li class="nav-item active">
            <%= link_to "Demo Sites", "#", class: "nav-link" %>
            <% link_to '<i class="fas fa-cogs fa-lg pr-2"></i>xxx'.html_safe, "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Pricing", root_path(anchor:"pricing"), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create a Website", new_website_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://avatars3.githubusercontent.com/u/4753571?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <!--%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %-->
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "View all my websites", "#", class: "dropdown-item" %>
              <%= link_to "Change your profile picture", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    
    </div>

  </div>
</nav>

app/views/websites/edit.html.erb
<h2>website Edit</h2>